import type {Metadata} from "next";
import {Gabarito} from "next/font/google";
import "./globals.css";
import React from "react";
import {CartProvider} from "@/context/CartContext";
import {AuthProvider} from "@/context/AuthContext";

const gabarito = Gabarito({
    variable: "--font-gabarito",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en" className={`${gabarito.className} ${gabarito.variable}`}>
        <body
            className={`${gabarito.className} ${gabarito.variable} font-sans antialiased`}
        >
        <AuthProvider>
            <CartProvider>{children}</CartProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
